### ISSUE TITLE
Inconsistent routing/binding behavior when using includes in templates

### ISSUE THREAD

**Issue by skylenewman** [pakyow/pakyow#90] opened 2015-07-28 12:32 UTC
* When binding `<head>` children, the `data-scope` needed to be on the `<head>` in the **template**.
* When binding `<ul>` and `<li>` elements inside a `<nav>`, the `data-scope` needed to be added to the **include**.

[Branch](https://github.com/OpenHuntsville/hntsvll/tree/28-abstract-menu-to-include)
[Commit](https://github.com/OpenHuntsville/hntsvll/commit/3c87563504be40dc9d1df340b8a9dfb57eb198c1)

**Comment by bryanp** [comment] 2015-07-28 21:00
Can you provide more detail as to what happens when you don't follow the two guidelines you posted? Just trying to get a better handle on the actual problem here.

**Comment by skylenewman** [comment] 2015-07-28 21:16
I guess this would be useful:

**Pakyow found something wrong.**

The error originated on line 214 of '/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_collection.rb' and generated the following stack trace:

undefined method `soft_copy' for nil:NilClass

/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_collection.rb:214:in `block in match'
/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_collection.rb:213:in `each'
/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_collection.rb:213:in `match'
/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_collection.rb:285:in `apply'
/home/kyle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/pakyow-92a9959d4cad/pakyow-presenter/lib/presenter/view_context.rb:29:in `block (2 levels) in <class:ViewContext>'
/home/kyle/Pakyow/hntsvll/app/lib/routes.rb:31:in `block (2 levels) in <top (required)>'

**Comment by bryanp** [comment] 2015-09-02 20:06
@skylenewman I'm still unable to reproduce with this information :(

Can you reproduce this in a small example app? That would help us get on the same page.

**Comment by bryanp** [comment] 2015-10-18 11:40
Closing until more information is provided. Happy to look into this more, just need some additional help getting to the point of reproducing the problem :)

**Closed by bryanp** 2015-10-18 11:40 UTC
Labels: Bug
